apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations }}
      annotations:  {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "mautic.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:  {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mautic.serviceAccountName" .}}
      containers:
      - name: mautic
        image: {{ include "mautic.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- if .Values.command }}
        command: {{- include "common.tplvalues.render" ( dict "value" .Values.command "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.args }}
        args: {{- include "common.tplvalues.render" ( dict "value" .Values.args "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ini-configmap
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
        - name: localphp-configmap
          mountPath: /var/www/html/app/config/local.php
          subPath: local.php
        - name: apacheports-configmap
          mountPath: /etc/apache2/ports.conf
          subPath: ports.conf
        {{- if .Values.extraVolumeMounts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
        {{- end }}
      volumes:
      {{- if not .Values.persistence.enabled }}
      - name: data
        emptyDir: {}
      {{- else }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "common.names.fullname" . }}-data
      {{- end }}
      - name: ini-configmap
        configMap:
          name: {{ include "common.names.fullname" . }}-phpini-configmap
      - name: localphp-configmap
        configMap:
          name: {{ include "common.names.fullname" . }}-localphp-configmap
      - name: apacheports-configmap
        configMap:
          name: {{ include "common.names.fullname" . }}-apacheports-configmap
      {{- if .Values.extraVolumes }}
      {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
