{{- if and .Values.rabbitmq.enabled .Values.rabbitmq.auth.existingPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.rabbitmqPasswordSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
{{- $password := default (randAlphaNum 24) .Values.rabbitmq.auth.password }}
data:
  rabbitmq-password: {{ $password | b64enc }}
{{- end }}
